module.exports = {
  LIBRARY_RETRIEVED: 'LIBRARY_RETRIEVED',
  STACK_DATA_RETRIEVED: 'STACK_DATA_RETRIEVED',
  EXAMPLES_RETRIEVED: 'EXAMPLES_RETRIEVED',
  SELECTED_LIBRARY: 'SELECTED_LIBRARY',
  SELECTED_METHOD: 'SELECTED_METHOD'
}