var mongoose = require('mongoose');
var http = require('http');
var Library = require('../server/libraries/libraryModel.js');
var zlib = require('zlib');
var Method = require('../server/methods/methodModel.js');

mongoose.connect('mongodb://localhost/flockdocs'); // connect to mongo database named flockdocs

Method.remove({}).exec().then(function(numRemoved) {
  console.log('Methods collection cleared. ' + numRemoved + ' documents removed.');

  Library.find().exec().then(function(libs) {
    // console.dir(libs);
    libs.forEach(function(lib) {
      //TODO scrape official library documentation URL for fresh methods??
      // console.dir(lib);
      lib.methods.forEach(function(method) {
        var options = {
          host:'api.stackexchange.com',
          path:'/2.2/search?page=1&pagesize=3&order=desc&sort=relevance&intitle=' +
           lib.name + '%20' + method + '&site=stackoverflow&key=ssNWU)nQZdqCIR3kXFf0IA((&filter=!-*f(6rkuau1P',
          headers: {
            'Accept-Encoding': 'gzip'
          }
        };

        http.request(options,function(res) {
          var gzstream = zlib.createGunzip();
          res.pipe(gzstream);

          var json = "";
          gzstream.on('data',function(chunk) {
            json+= chunk;
          });

          gzstream.on('end', function() {
            // console.log(json);

            var data = JSON.parse(json);
            console.log(lib.name + "::" + method);
            console.log("QUOTA REMAINING:" + data.quota_remaining);
            // console.dir(data.items[0]);

            if(data.items.length) {
              Method.create({name: method, library: lib.name, topQuestions: data.items}).then(function(doc,err) {
                if(err){
                  console.dir(err);
                }
              });
            }
          });
        }).end();

        //TODO autogenerated question answers... - autogenerate questions?
      
        //followed by updating the data in the mongoDB..
      });
    });
  });
});
